apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: trisa
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy-dev:933e67a9ecac814839f514fb5c31c78f3d33e5fe
        ports:
        - containerPort: 8080
          protocol: TCP
          name: proxy
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
        resources: {}
      volumes:
      - name: config
        configMap:
          name: envoy-conf
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: trisa
spec:
  ports:
  - port: 8080
    targetPort: proxy
    name: proxy
  selector:
    app: envoy
  type: ClusterIP