apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: testnet
build:
  artifacts:
  # - image: trisa/demo-bff
  #   context: .
  #   docker:
  #     dockerfile: containers/demo/bff/Dockerfile
  # - image: trisa/demo-npm
  #   context: .
  #   docker:
  #     dockerfile: containers/demo/npm/Dockerfile
  - image: trisa/rvasp
    context: .
    docker:
      dockerfile: containers/rvasp/Dockerfile
  local:
    push: true
    useDockerCLI: true