apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: testnet
build:
  artifacts:
  - image: trisa/demo-bff
    context: .
    docker:
      dockerfile: containers/demo/bff/Dockerfile
  - image: trisa/demo-npm
    context: .
    docker:
      dockerfile: containers/demo/npm/Dockerfile
  - image: trisa/rvasp
    context: .
    docker:
      dockerfile: containers/rvasp/Dockerfile
  - image: trisa/rvasp-alice
    context: .
    requires:
    - image: trisa/rvasp
      alias: BASE
    docker:
      dockerfile: containers/rvasp/alice/Dockerfile
  - image: trisa/rvasp-bob
    context: .
    requires:
    - image: trisa/rvasp
      alias: BASE
    docker:
      dockerfile: containers/rvasp/bob/Dockerfile
  - image: trisa/rvasp-evil
    context: .
    requires:
    - image: trisa/rvasp
      alias: BASE
    docker:
      dockerfile: containers/rvasp/evil/Dockerfile
  local:
    push: true
    useDockerCLI: true