FROM nginx

COPY web/placeholder/landing/index.html /usr/share/nginx/html/
COPY web/placeholder/landing/favicon.gif /usr/share/nginx/html/
COPY web/placeholder/landing/background.jpg /usr/share/nginx/html/