version: "3"
services:
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rvasp

  openvasp:
    build: 
      context: ../
      dockerfile: ./containers/openvasp/Dockerfile
    ports:
      - 4436:4436
      - 5432:5432
    environment:
      - OPENVASP_DATABASE_DSN=postgres://postgres:postgres@openvasp:5432/openvasp?sslmode=disable

  migrate:
    build:
      context: ../
      dockerfile: ./containers/db/Dockerfile
    image: trisa/rvasp-migrate
    depends_on:
      - db
    environment:
      - RVASP_DATABASE_DSN=postgres://postgres:postgres@db:5432/rvasp?sslmode=disable
      - RVASP_FIXTURES_PATH=/fixtures
      - RVASP_DATABASE_MAX_RETRIES=5
    volumes:
      - ../fixtures/rvasps:/fixtures

  gds:
    image: trisa/gds:latest
    init: true
    ports:
      - 4433:4433
    volumes:
      - ../fixtures/db:/data
    environment:
      - GDS_DIRECTORY_ID=trisatest.net
      - GDS_SECRET_KEY=supersecretsquirrel
      - GDS_MAINTENANCE=false
      - GDS_LOG_LEVEL=debug
      - GDS_CONSOLE_LOG=true
      - GDS_API_ENABLED=true
      - GDS_BIND_ADDR=:4433
      - GDS_ADMIN_ENABLED=false
      - GDS_MEMBERS_ENABLED=false
      - GDS_MEMBERS_INSECURE=true
      - GDS_DATABASE_URL=leveldb:////data
      - GDS_DATABASE_REINDEX_ON_BOOT=false
      - SECTIGO_TESTING=true
      - GDS_EMAIL_TESTING=true
      - GDS_EMAIL_STORAGE=/data/emails
      - GDS_CERTMAN_INTERVAL=96h
      - GDS_BACKUP_ENABLED=false
      - GDS_SECRETS_TESTING=true

  alice:
    image: trisa/rvasp:latest
    depends_on:
      - migrate
      - gds
    ports:
      - 5434:4434
      - 5435:4435
    environment:
      - RVASP_NAME=alice
      - RVASP_DATABASE_DSN=postgres://postgres:postgres@db:5432/rvasp?sslmode=disable
      - RVASP_CERT_PATH=/certs/cert.pem
      - RVASP_TRUST_CHAIN_PATH=/certs/cert.pem
      - RVASP_GDS_URL=gds:4433
      - RVASP_GDS_INSECURE=true
      - RVASP_DATABASE_MAX_RETRIES=5
      - RVASP_LOG_LEVEL
      - RVASP_CONSOLE_LOG=true
      - RVASP_ASYNC_INTERVAL
      - RVASP_ASYNC_NOT_BEFORE
      - RVASP_ASYNC_NOT_AFTER
    volumes:
      - ../fixtures/certs/alice:/certs

  bob:
    image: trisa/rvasp:latest
    depends_on:
      - migrate
      - gds
    ports:
      - 6434:4434
      - 6435:4435
    environment:
      - RVASP_NAME=bob
      - RVASP_DATABASE_DSN=postgres://postgres:postgres@db:5432/rvasp?sslmode=disable
      - RVASP_CERT_PATH=/certs/cert.pem
      - RVASP_TRUST_CHAIN_PATH=/certs/cert.pem
      - RVASP_GDS_URL=gds:4433
      - RVASP_GDS_INSECURE=true
      - RVASP_DATABASE_MAX_RETRIES=5
      - RVASP_LOG_LEVEL
      - RVASP_CONSOLE_LOG=true
      - RVASP_ASYNC_INTERVAL
      - RVASP_ASYNC_NOT_BEFORE
      - RVASP_ASYNC_NOT_AFTER
    volumes:
      - ../fixtures/certs/bob:/certs

  evil:
    image: trisa/rvasp:latest
    depends_on:
      - migrate
      - gds
    ports:
      - 7434:4434
      - 7435:4435
    environment:
      - RVASP_NAME=evil
      - RVASP_DATABASE_DSN=postgres://postgres:postgres@db:5432/rvasp?sslmode=disable
      - RVASP_CERT_PATH=/certs/cert.pem
      - RVASP_TRUST_CHAIN_PATH=/certs/cert.pem
      - RVASP_GDS_URL=gds:4433
      - RVASP_GDS_INSECURE=true
      - RVASP_DATABASE_MAX_RETRIES=5
      - RVASP_LOG_LEVEL
      - RVASP_CONSOLE_LOG=true
      - RVASP_ASYNC_INTERVAL
      - RVASP_ASYNC_NOT_BEFORE
      - RVASP_ASYNC_NOT_AFTER
    volumes:
      - ../fixtures/certs/evil:/certs

  charlie:
    image: trisa/rvasp:latest
    depends_on:
      - migrate
      - gds
    ports:
      - 8434:4434
      - 8435:4435
    environment:
      - RVASP_NAME=charlie
      - RVASP_DATABASE_DSN=postgres://postgres:postgres@db:5432/rvasp?sslmode=disable
      - RVASP_CERT_PATH=/certs/cert.pem
      - RVASP_TRUST_CHAIN_PATH=/certs/cert.pem
      - RVASP_GDS_URL=gds:4433
      - RVASP_GDS_INSECURE=true
      - RVASP_DATABASE_MAX_RETRIES=5
      - RVASP_LOG_LEVEL
      - RVASP_CONSOLE_LOG=true
      - RVASP_ASYNC_INTERVAL
      - RVASP_ASYNC_NOT_BEFORE
      - RVASP_ASYNC_NOT_AFTER
    volumes:
      - ../fixtures/certs/charlie:/certs

  vaspdirectory:
    build:
      context: ../
      dockerfile: ./containers/placeholder/trisads/Dockerfile
    image: trisa/placeholder:trisads
    ports:
      - 8080:80
    profiles:
      - placeholder

  vaspbot:
    build:
      context: ../
      dockerfile: ./containers/placeholder/vaspbot/Dockerfile
    image: trisa/placeholder:vaspbot
    ports:
      - 8081:80
    profiles:
      - placeholder

  trisatest:
    build:
      context: ../
      dockerfile: ./containers/placeholder/landing/Dockerfile
    image: trisa/placeholder:landing
    ports:
      - 8082:80
    profiles:
      - placeholder