FROM nginx

COPY web/placeholder/trisads/index.html /usr/share/nginx/html/
COPY web/placeholder/trisads/favicon.gif /usr/share/nginx/html/
COPY web/placeholder/trisads/background.jpg /usr/share/nginx/html/