version: "3.8"
services:
  web:
    build: npm
    ports:
     - "3000:3000"
    environment:
     - TEST=1
    stdin_open: true
    links:
     - bff
  bff:
    build: bff
    ports:
     - "5000:5000"
    environment:
     - TEST=1
