apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trisads
  namespace: trisa
  labels:
    app: trisads
spec:
  serviceName: trisads
  replicas: 0
  selector:
    matchLabels:
      app: trisads
  template:
    metadata:
      labels:
        app: trisads
    spec:
      containers:
      - name: trisads
        image: trisa/gds:1.0-rc.5
        ports:
        - containerPort: 443
          protocol: TCP
          name: grpc
        volumeMounts:
        - name: dsdata
          mountPath: /data
        - name: dscerts
          mountPath: /certs
        - name: dsgcpsa
          mountPath: /creds
          readOnly: true
        resources: {}
        env:
        - name: GDS_BIND_ADDR
          value: :443
        - name: GDS_DIRECTORY_ID
          value: trisa.directory
        - name: GDS_DATABASE_URL
          value: leveldb:////data
        - name: GDS_LOG_LEVEL
          value: info
        - name: GDS_SERVICE_EMAIL
          value: "TRISA Directory Service <admin@trisa.directory>"
        - name: GDS_ADMIN_EMAIL
          value: "TRISA Admins <admin@trisa.io>"
        - name: SECTIGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: sectigo-creds
              key: username
        - name: SECTIGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sectigo-creds
              key: password
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-apikey
              key: apikey
        - name: GDS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: trisads-secret
              key: passphrase
        - name: GDS_CERTMAN_INTERVAL
          value: 10m
        - name: GDS_CERTMAN_STORAGE
          value: /certs
        - name: GDS_BACKUP_ENABLED
          value: "true"
        - name: GDS_BACKUP_INTERVAL
          value: 1h
        - name: GDS_BACKUP_STORAGE
          value: /certs/backups
        - name: GDS_BACKUP_KEEP
          value: "1"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /creds/gcp-trisads-sa.json
        - name: GOOGLE_PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: project
      volumes:
      - name: dsgcpsa
        secret:
          secretName: gcp-trisads-sa
          items:
          - key: serviceAccount
            path: gcp-trisads-sa.json
  volumeClaimTemplates:
  - metadata:
      name: dsdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
  # TODO: change to emptyDir
  - metadata:
      name: dscerts
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: trisads-service
  namespace: trisa
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 443
    protocol: TCP
    targetPort: grpc
  selector:
    app: trisads
