apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trisads
  namespace: trisa
  labels:
    app: trisads
spec:
  serviceName: trisads
  replicas: 1
  selector:
    matchLabels:
      app: trisads
  template:
    metadata:
      labels:
        app: trisads
    spec:
      containers:
      - name: trisads
        image: trisa/gds:de9902f
        ports:
        - containerPort: 443
          protocol: TCP
          name: grpc
        volumeMounts:
        - name: dsdata
          mountPath: /data
        - name: dscerts
          mountPath: /certs
        resources: {}
        env:
        - name: GDS_MAINTENANCE
          value: "true"
        - name: GDS_BIND_ADDR
          value: :443
        - name: GDS_DIRECTORY_ID
          value: vaspdirectory.net
        - name: GDS_DATABASE_URL
          value: leveldb:////data
        - name: GDS_SERVICE_EMAIL
          value: admin@vaspdirectory.net
        - name: GDS_ADMIN_EMAIL
          value: admin@trisa.io
        - name: GDS_LOG_LEVEL
          value: info
        - name: SECTIGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: sectigo-creds
              key: username
        - name: SECTIGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sectigo-creds
              key: password
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-apikey
              key: apikey
        - name: GDS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: trisads-secret
              key: passphrase
        - name: GDS_CERTMAN_INTERVAL
          value: 2m
        - name: GDS_CERTMAN_STORAGE
          value: /certs
        - name: GDS_BACKUP_ENABLED
          value: "true"
        - name: GDS_BACKUP_INTERVAL
          value: 1h
        - name: GDS_BACKUP_STORAGE
          value: /certs/backups
        - name: GDS_BACKUP_KEEP
          value: "1"
  volumeClaimTemplates:
  - metadata:
      name: dsdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
  - metadata:
      name: dscerts
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: trisads-service
  namespace: trisa
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 443
    protocol: TCP
    targetPort: grpc
  selector:
    app: trisads
