// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package ivms101

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Originator struct {
	// Definition: the account holder who allows the VA transfer from that account or, where there
	// is no account, the natural or legal person that places the order with the originating VASP
	// to perform the VA transfer.
	// One or More
	OriginatorPersons []*Person `protobuf:"bytes,1,rep,name=originator_persons,json=originatorPersons,proto3" json:"originator_persons,omitempty"`
	// Definition: Identifier of an account that is used to process the transaction. The value
	// for this element is case-sensitive.
	// Datatype: “Max100Text”
	// Zero or More
	AccountNumbers       []string `protobuf:"bytes,2,rep,name=account_numbers,json=accountNumbers,proto3" json:"account_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Originator) Reset()         { *m = Originator{} }
func (m *Originator) String() string { return proto.CompactTextString(m) }
func (*Originator) ProtoMessage()    {}
func (*Originator) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{0}
}

func (m *Originator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Originator.Unmarshal(m, b)
}
func (m *Originator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Originator.Marshal(b, m, deterministic)
}
func (m *Originator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Originator.Merge(m, src)
}
func (m *Originator) XXX_Size() int {
	return xxx_messageInfo_Originator.Size(m)
}
func (m *Originator) XXX_DiscardUnknown() {
	xxx_messageInfo_Originator.DiscardUnknown(m)
}

var xxx_messageInfo_Originator proto.InternalMessageInfo

func (m *Originator) GetOriginatorPersons() []*Person {
	if m != nil {
		return m.OriginatorPersons
	}
	return nil
}

func (m *Originator) GetAccountNumbers() []string {
	if m != nil {
		return m.AccountNumbers
	}
	return nil
}

type Beneficiary struct {
	// Definition: the natural or legal person or legal arrangement who is identified by the originator
	// as the receiver of the requested VA transfer.
	// One or More
	BeneficiaryPersons []*Person `protobuf:"bytes,1,rep,name=beneficiary_persons,json=beneficiaryPersons,proto3" json:"beneficiary_persons,omitempty"`
	// Definition: Identifier of an account that is used to process the transaction. The value
	// for this element is case-sensitive.
	// Datatype: “Max100Text”
	// Zero or More
	AccountNumbers       []string `protobuf:"bytes,2,rep,name=account_numbers,json=accountNumbers,proto3" json:"account_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Beneficiary) Reset()         { *m = Beneficiary{} }
func (m *Beneficiary) String() string { return proto.CompactTextString(m) }
func (*Beneficiary) ProtoMessage()    {}
func (*Beneficiary) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1}
}

func (m *Beneficiary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Beneficiary.Unmarshal(m, b)
}
func (m *Beneficiary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Beneficiary.Marshal(b, m, deterministic)
}
func (m *Beneficiary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Beneficiary.Merge(m, src)
}
func (m *Beneficiary) XXX_Size() int {
	return xxx_messageInfo_Beneficiary.Size(m)
}
func (m *Beneficiary) XXX_DiscardUnknown() {
	xxx_messageInfo_Beneficiary.DiscardUnknown(m)
}

var xxx_messageInfo_Beneficiary proto.InternalMessageInfo

func (m *Beneficiary) GetBeneficiaryPersons() []*Person {
	if m != nil {
		return m.BeneficiaryPersons
	}
	return nil
}

func (m *Beneficiary) GetAccountNumbers() []string {
	if m != nil {
		return m.AccountNumbers
	}
	return nil
}

type OriginatingVasp struct {
	// Definition: refers to the VASP which initiates the VA transfer, and transfers the VA
	// upon receiving the request for a VA transfer on behalf of the originator.
	// Optional
	OriginatingVasp      *Person  `protobuf:"bytes,1,opt,name=originating_vasp,json=originatingVasp,proto3" json:"originating_vasp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginatingVasp) Reset()         { *m = OriginatingVasp{} }
func (m *OriginatingVasp) String() string { return proto.CompactTextString(m) }
func (*OriginatingVasp) ProtoMessage()    {}
func (*OriginatingVasp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{2}
}

func (m *OriginatingVasp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginatingVasp.Unmarshal(m, b)
}
func (m *OriginatingVasp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginatingVasp.Marshal(b, m, deterministic)
}
func (m *OriginatingVasp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginatingVasp.Merge(m, src)
}
func (m *OriginatingVasp) XXX_Size() int {
	return xxx_messageInfo_OriginatingVasp.Size(m)
}
func (m *OriginatingVasp) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginatingVasp.DiscardUnknown(m)
}

var xxx_messageInfo_OriginatingVasp proto.InternalMessageInfo

func (m *OriginatingVasp) GetOriginatingVasp() *Person {
	if m != nil {
		return m.OriginatingVasp
	}
	return nil
}

type BeneficiaryVasp struct {
	// Definition: the VASP which receives the transfer of a virtual asset from the originating VASP
	// directly or through an intermediary VASP and makes the funds available to the beneficiary.
	// Optional
	BeneficiaryVasp      *Person  `protobuf:"bytes,1,opt,name=beneficiary_vasp,json=beneficiaryVasp,proto3" json:"beneficiary_vasp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeneficiaryVasp) Reset()         { *m = BeneficiaryVasp{} }
func (m *BeneficiaryVasp) String() string { return proto.CompactTextString(m) }
func (*BeneficiaryVasp) ProtoMessage()    {}
func (*BeneficiaryVasp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{3}
}

func (m *BeneficiaryVasp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeneficiaryVasp.Unmarshal(m, b)
}
func (m *BeneficiaryVasp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeneficiaryVasp.Marshal(b, m, deterministic)
}
func (m *BeneficiaryVasp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeneficiaryVasp.Merge(m, src)
}
func (m *BeneficiaryVasp) XXX_Size() int {
	return xxx_messageInfo_BeneficiaryVasp.Size(m)
}
func (m *BeneficiaryVasp) XXX_DiscardUnknown() {
	xxx_messageInfo_BeneficiaryVasp.DiscardUnknown(m)
}

var xxx_messageInfo_BeneficiaryVasp proto.InternalMessageInfo

func (m *BeneficiaryVasp) GetBeneficiaryVasp() *Person {
	if m != nil {
		return m.BeneficiaryVasp
	}
	return nil
}

type IntermediaryVasp struct {
	// Definition: the VASP in a serial chain that receives and retransmits a VA transfer on behalf of the originating VASP
	// and the beneficiary VASP, or another intermediary VASP.
	// Required
	IntermediaryVasp *Person `protobuf:"bytes,1,opt,name=intermediary_vasp,json=intermediaryVasp,proto3" json:"intermediary_vasp,omitempty"`
	// Definition: the sequence in a serial chain at which the corresponding intermediary VASP participates in the transfer.
	// Constraints: totalDigits: 18; fractionDigits: 0
	// Required
	Sequence             uint64   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntermediaryVasp) Reset()         { *m = IntermediaryVasp{} }
func (m *IntermediaryVasp) String() string { return proto.CompactTextString(m) }
func (*IntermediaryVasp) ProtoMessage()    {}
func (*IntermediaryVasp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{4}
}

func (m *IntermediaryVasp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntermediaryVasp.Unmarshal(m, b)
}
func (m *IntermediaryVasp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntermediaryVasp.Marshal(b, m, deterministic)
}
func (m *IntermediaryVasp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntermediaryVasp.Merge(m, src)
}
func (m *IntermediaryVasp) XXX_Size() int {
	return xxx_messageInfo_IntermediaryVasp.Size(m)
}
func (m *IntermediaryVasp) XXX_DiscardUnknown() {
	xxx_messageInfo_IntermediaryVasp.DiscardUnknown(m)
}

var xxx_messageInfo_IntermediaryVasp proto.InternalMessageInfo

func (m *IntermediaryVasp) GetIntermediaryVasp() *Person {
	if m != nil {
		return m.IntermediaryVasp
	}
	return nil
}

func (m *IntermediaryVasp) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type TransferPath struct {
	// Definition: the intermediary VASP(s) participating in a serial chain that receive and
	// retransmit a VA transfer on behalf of the originating VASP and the beneficiary VASP, or
	// another intermediary VASP, together with their corresponding sequence number.
	// Zero or More
	TransferPath         []*IntermediaryVasp `protobuf:"bytes,1,rep,name=transfer_path,json=transferPath,proto3" json:"transfer_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TransferPath) Reset()         { *m = TransferPath{} }
func (m *TransferPath) String() string { return proto.CompactTextString(m) }
func (*TransferPath) ProtoMessage()    {}
func (*TransferPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{5}
}

func (m *TransferPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferPath.Unmarshal(m, b)
}
func (m *TransferPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferPath.Marshal(b, m, deterministic)
}
func (m *TransferPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferPath.Merge(m, src)
}
func (m *TransferPath) XXX_Size() int {
	return xxx_messageInfo_TransferPath.Size(m)
}
func (m *TransferPath) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferPath.DiscardUnknown(m)
}

var xxx_messageInfo_TransferPath proto.InternalMessageInfo

func (m *TransferPath) GetTransferPath() []*IntermediaryVasp {
	if m != nil {
		return m.TransferPath
	}
	return nil
}

type PayloadMetadata struct {
	// Definition: the method used to map from a national system of writing to Latin script.
	// Zero or More
	TransliterationMethod []TransliterationMethodCode `protobuf:"varint,1,rep,packed,name=transliteration_method,json=transliterationMethod,proto3,enum=ivms101.TransliterationMethodCode" json:"transliteration_method,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                    `json:"-"`
	XXX_unrecognized      []byte                      `json:"-"`
	XXX_sizecache         int32                       `json:"-"`
}

func (m *PayloadMetadata) Reset()         { *m = PayloadMetadata{} }
func (m *PayloadMetadata) String() string { return proto.CompactTextString(m) }
func (*PayloadMetadata) ProtoMessage()    {}
func (*PayloadMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{6}
}

func (m *PayloadMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadMetadata.Unmarshal(m, b)
}
func (m *PayloadMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadMetadata.Marshal(b, m, deterministic)
}
func (m *PayloadMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadMetadata.Merge(m, src)
}
func (m *PayloadMetadata) XXX_Size() int {
	return xxx_messageInfo_PayloadMetadata.Size(m)
}
func (m *PayloadMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadMetadata proto.InternalMessageInfo

func (m *PayloadMetadata) GetTransliterationMethod() []TransliterationMethodCode {
	if m != nil {
		return m.TransliterationMethod
	}
	return nil
}

type IdentityPayload struct {
	Originator           *Originator      `protobuf:"bytes,1,opt,name=originator,proto3" json:"originator,omitempty"`
	Beneficiary          *Beneficiary     `protobuf:"bytes,2,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	OriginatingVasp      *OriginatingVasp `protobuf:"bytes,3,opt,name=originating_vasp,json=originatingVasp,proto3" json:"originating_vasp,omitempty"`
	BeneficiaryVasp      *BeneficiaryVasp `protobuf:"bytes,4,opt,name=beneficiary_vasp,json=beneficiaryVasp,proto3" json:"beneficiary_vasp,omitempty"`
	TransferPath         *TransferPath    `protobuf:"bytes,5,opt,name=transfer_path,json=transferPath,proto3" json:"transfer_path,omitempty"`
	PayloadMetadata      *PayloadMetadata `protobuf:"bytes,6,opt,name=payload_metadata,json=payloadMetadata,proto3" json:"payload_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IdentityPayload) Reset()         { *m = IdentityPayload{} }
func (m *IdentityPayload) String() string { return proto.CompactTextString(m) }
func (*IdentityPayload) ProtoMessage()    {}
func (*IdentityPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{7}
}

func (m *IdentityPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityPayload.Unmarshal(m, b)
}
func (m *IdentityPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityPayload.Marshal(b, m, deterministic)
}
func (m *IdentityPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityPayload.Merge(m, src)
}
func (m *IdentityPayload) XXX_Size() int {
	return xxx_messageInfo_IdentityPayload.Size(m)
}
func (m *IdentityPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityPayload.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityPayload proto.InternalMessageInfo

func (m *IdentityPayload) GetOriginator() *Originator {
	if m != nil {
		return m.Originator
	}
	return nil
}

func (m *IdentityPayload) GetBeneficiary() *Beneficiary {
	if m != nil {
		return m.Beneficiary
	}
	return nil
}

func (m *IdentityPayload) GetOriginatingVasp() *OriginatingVasp {
	if m != nil {
		return m.OriginatingVasp
	}
	return nil
}

func (m *IdentityPayload) GetBeneficiaryVasp() *BeneficiaryVasp {
	if m != nil {
		return m.BeneficiaryVasp
	}
	return nil
}

func (m *IdentityPayload) GetTransferPath() *TransferPath {
	if m != nil {
		return m.TransferPath
	}
	return nil
}

func (m *IdentityPayload) GetPayloadMetadata() *PayloadMetadata {
	if m != nil {
		return m.PayloadMetadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Originator)(nil), "ivms101.Originator")
	proto.RegisterType((*Beneficiary)(nil), "ivms101.Beneficiary")
	proto.RegisterType((*OriginatingVasp)(nil), "ivms101.OriginatingVasp")
	proto.RegisterType((*BeneficiaryVasp)(nil), "ivms101.BeneficiaryVasp")
	proto.RegisterType((*IntermediaryVasp)(nil), "ivms101.IntermediaryVasp")
	proto.RegisterType((*TransferPath)(nil), "ivms101.TransferPath")
	proto.RegisterType((*PayloadMetadata)(nil), "ivms101.PayloadMetadata")
	proto.RegisterType((*IdentityPayload)(nil), "ivms101.IdentityPayload")
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_61c7956abb761639) }

var fileDescriptor_61c7956abb761639 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x4f, 0xdb, 0x30,
	0x14, 0x56, 0x29, 0x63, 0xe3, 0x15, 0x9a, 0x62, 0xc6, 0x94, 0xf5, 0x54, 0xe5, 0xb2, 0x9e, 0xd0,
	0x28, 0xd2, 0x0e, 0x68, 0x42, 0x13, 0x9c, 0x38, 0x94, 0x55, 0x16, 0x9a, 0xb4, 0x5d, 0x22, 0xb7,
	0x31, 0xd4, 0x52, 0x63, 0x67, 0xf6, 0x0b, 0x5a, 0x7f, 0xc2, 0xfe, 0xf5, 0x54, 0xc7, 0x4d, 0x9c,
	0xa4, 0x62, 0xe2, 0x96, 0xf7, 0xe5, 0xbd, 0xef, 0xb3, 0xdf, 0xf7, 0xc9, 0xd0, 0x17, 0x09, 0x97,
	0x28, 0x70, 0x7d, 0x9e, 0x69, 0x85, 0x8a, 0xbc, 0x15, 0xcf, 0xa9, 0xb9, 0xf8, 0x7c, 0x31, 0x3c,
	0x76, 0x1f, 0x05, 0x3e, 0x04, 0x2e, 0xf3, 0xb4, 0xf8, 0x8e, 0x72, 0x80, 0xef, 0x5a, 0x3c, 0x09,
	0xc9, 0x50, 0x69, 0x72, 0x0d, 0x44, 0x95, 0x55, 0x9c, 0x71, 0x6d, 0x94, 0x34, 0x61, 0x67, 0xd4,
	0x1d, 0xf7, 0x26, 0xc1, 0xf9, 0x96, 0x65, 0x66, 0x71, 0x7a, 0x52, 0xb5, 0x16, 0x88, 0x21, 0x9f,
	0x20, 0x60, 0x8b, 0x85, 0xca, 0x25, 0xc6, 0x32, 0x4f, 0xe7, 0x5c, 0x9b, 0x70, 0x6f, 0xd4, 0x1d,
	0x1f, 0xd2, 0xbe, 0x83, 0xef, 0x0b, 0x34, 0xfa, 0x03, 0xbd, 0x1b, 0x2e, 0xf9, 0xa3, 0x58, 0x08,
	0xa6, 0xd7, 0xe4, 0x1b, 0x9c, 0xce, 0xab, 0xf2, 0x7f, 0xc2, 0xc4, 0xeb, 0x7d, 0xb5, 0xf2, 0x14,
	0x82, 0xed, 0x85, 0x85, 0x7c, 0xfa, 0xc1, 0x4c, 0x46, 0xae, 0x60, 0xa0, 0x2a, 0x28, 0x7e, 0x66,
	0x26, 0x0b, 0x3b, 0xa3, 0xce, 0x2e, 0xe9, 0x40, 0xd5, 0x67, 0x37, 0x74, 0xde, 0x45, 0xb6, 0x74,
	0xfe, 0x65, 0x5e, 0xa4, 0x9b, 0xd7, 0x67, 0xa3, 0x15, 0x0c, 0xee, 0x24, 0x72, 0x9d, 0xf2, 0xa4,
	0xe4, 0xfb, 0x0a, 0x27, 0xc2, 0xc3, 0x5e, 0x24, 0x1c, 0x88, 0xe6, 0xf4, 0x10, 0xde, 0x19, 0xfe,
	0x3b, 0xe7, 0x72, 0xc1, 0xc3, 0xbd, 0x51, 0x67, 0xbc, 0x4f, 0xcb, 0x3a, 0xba, 0x87, 0xa3, 0x07,
	0xcd, 0xa4, 0x79, 0xe4, 0x7a, 0xc6, 0x70, 0x49, 0xae, 0xe1, 0x18, 0x5d, 0x1d, 0x67, 0x0c, 0x97,
	0xce, 0x80, 0x8f, 0xa5, 0x4a, 0xf3, 0x6c, 0xf4, 0x08, 0xbd, 0xf9, 0x68, 0x05, 0xc1, 0x8c, 0xad,
	0x57, 0x8a, 0x25, 0x53, 0x8e, 0x2c, 0x61, 0xc8, 0xc8, 0x4f, 0xf8, 0x60, 0x5b, 0x56, 0x02, 0xb9,
	0x66, 0x28, 0x94, 0x8c, 0x53, 0x8e, 0x4b, 0x95, 0x58, 0xee, 0xfe, 0x24, 0x2a, 0xb9, 0x1f, 0xea,
	0x6d, 0x53, 0xdb, 0x75, 0xab, 0x12, 0x4e, 0xcf, 0x70, 0xd7, 0xaf, 0xe8, 0x6f, 0x17, 0x82, 0x3b,
	0x97, 0x78, 0x27, 0x4b, 0x2e, 0x01, 0xaa, 0x54, 0xba, 0x25, 0x9d, 0x96, 0x12, 0x55, 0xd2, 0xa9,
	0xd7, 0x46, 0xbe, 0x40, 0xcf, 0xf3, 0xc1, 0x6e, 0xa9, 0x37, 0x79, 0x5f, 0x4e, 0x79, 0xfe, 0x52,
	0xbf, 0x91, 0xdc, 0xee, 0xc8, 0x4d, 0xd7, 0x0e, 0x87, 0x2d, 0x49, 0x97, 0x97, 0x56, 0x80, 0x36,
	0x24, 0xad, 0xb4, 0xec, 0x37, 0x48, 0x1a, 0x09, 0x6b, 0xc5, 0x86, 0x5c, 0x35, 0x8d, 0x7b, 0x63,
	0x19, 0xce, 0xea, 0xcb, 0x75, 0x36, 0xd5, 0x4d, 0xdb, 0x1c, 0x20, 0x2b, 0xb6, 0xb7, 0x71, 0xc6,
	0xba, 0x16, 0x1e, 0x34, 0x0e, 0xd0, 0x70, 0x95, 0x06, 0x59, 0x1d, 0xb8, 0x39, 0xfc, 0xb5, 0x7d,
	0x6c, 0xe6, 0x07, 0xf6, 0x61, 0xb9, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x45, 0x9f, 0x2e, 0xff,
	0x8e, 0x04, 0x00, 0x00,
}
