FROM nginx

COPY web/placeholder/vaspbot/index.html /usr/share/nginx/html/
COPY web/placeholder/vaspbot/favicon.gif /usr/share/nginx/html/
COPY web/placeholder/vaspbot/background.jpg /usr/share/nginx/html/