apiVersion: apps/v1
kind: Deployment
metadata:
  name: demobff-alice
  namespace: trisa
  labels:
    app: demobff-alice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demobff-alice
  template:
    metadata:
      labels:
        app: demobff-alice
    spec:
      containers:
      - name: demobff-alice
        image: trisa/demo-bff:7fd04b1
        ports:
        - containerPort: 8000
          protocol: TCP
          name: http
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demobff-alice-service
  namespace: trisa
spec:
  ports:
  - port: 8000
    targetPort: http
    name: http
  selector:
    app: demobff-alice
