apiVersion: apps/v1
kind: Deployment
metadata:
  name: demobff-bob
  namespace: trisa
  labels:
    app: demobff-bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demobff-bob
  template:
    metadata:
      labels:
        app: demobff-bob
    spec:
      containers:
      - name: demobff-bob
        image: trisa/demo-bff:alpha-14-ge61211d
        ports:
        - containerPort: 8000
          protocol: TCP
          name: http
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demobff-bob-service
  namespace: trisa
spec:
  ports:
  - port: 8000
    targetPort: http
    name: http
  selector:
    app: demobff-bob
