apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: trisa
  labels:
    app: demo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
      - name: demo-web
        image: trisa/demo-npm:ed8e197
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web-service
  namespace: trisa
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  selector:
    app: demo-web