apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvasp-alice
  namespace: trisa
  labels:
    app: rvasp-alice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvasp-alice
  template:
    metadata:
      labels:
        app: rvasp-alice
    spec:
      containers:
      - name: rvasp-alice
        image: trisa/rvasp-alice:alpha-8-g2d7123d
        ports:
        - containerPort: 4434
          protocol: TCP
          name: grpc-rvasp
        - containerPort: 4435
          protocol: TCP
          name: grpc-trisa
        volumeMounts:
        - name: certs
          mountPath: "/data/certs"
          readOnly: true
        resources: {}
        env:
        - name: RVASP_NAME
          value: "api.alice.vaspbot.net"
        - name: RVASP_BIND_ADDR
          value: ":4434"
        - name: RVASP_TRISA_BIND_ADDR
          value: ":4435"
        - name: RVASP_DATABASE
          value: "/data/rvasp.db"
        - name: RVASP_CERT_PATH
          value: "/data/certs/api.alice.vaspbot.net.gz"
        - name: RVASP_TRUST_CHAIN_PATH
          value: "/data/certs/trisa.zip"
        - name: RVASP_DIRECTORY_SERVICE_URL
          value: "api.vaspdirectory.net:443"
        - name: RVASP_LOG_LEVEL
          value: info
      volumes:
      - name: certs
        secret:
          secretName: alice-certs
          items:
          - key: mtls
            path: api.alice.vaspbot.net.gz
          - key: chain
            path: trisa.zip
---
apiVersion: v1
kind: Service
metadata:
  name: rvasp-alice-service
  namespace: trisa
spec:
  type: ClusterIP
  ports:
  - name: grpc-rvasp
    port: 4434
    protocol: TCP
    targetPort: grpc-rvasp
  selector:
    app: rvasp-alice