name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: staticcheck ./...
        
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          
      - name: Install Go Dependencies
        run: |
          go version
          go install github.com/kevinburke/go-bindata/go-bindata@v3.23.0
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0

      - name: Install Python Dependencies
        run: pip install -r lib/python/rvaspy/requirements.txt
          
      - name: Code Generation
        run: go generate ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
